#!/bin/bash
FEYNMAN_TOP_DIR=$(git rev-parse --show-toplevel)
alias mk='cd ${FEYNMAN_TOP_DIR}/; ./buildcmd.sh'
alias pg='${FEYNMAN_TOP_DIR}/build/pahole -G -C page vmlinux'
alias pd='${FEYNMAN_TOP_DIR}/build/pahole -G -C desc_struct vmlinux'
alias wpg='echo ${FEYNMAN_TOP_DIR}/build/pahole -G -C page vmlinux'
