#!/bin/bash
FEYNMAN_TOP_DIR=$(git rev-parse --show-toplevel)
alias mk='cd ${FEYNMAN_TOP_DIR}/; ./buildcmd.sh'
alias pg='${FEYNMAN_TOP_DIR}/build/pahole -G -C page vmlinux'
alias npg='${FEYNMAN_TOP_DIR}/build/pahole -C page vmlinux'
alias pd='${FEYNMAN_TOP_DIR}/build/pahole -G -C desc_struct vmlinux'
alias npd='${FEYNMAN_TOP_DIR}/build/pahole  -C desc_struct vmlinux'
alias pe='${FEYNMAN_TOP_DIR}/build/pahole -G -C edd vmlinux'
alias npe='${FEYNMAN_TOP_DIR}/build/pahole  -C edd vmlinux'
alias wpg='echo ${FEYNMAN_TOP_DIR}/build/pahole -G -C page vmlinux'
alias pdd='${FEYNMAN_TOP_DIR}/build/pahole -G -C edd_device_params vmlinux'
alias npdd='${FEYNMAN_TOP_DIR}/build/pahole  -C edd_device_params vmlinux'
alias pss='${FEYNMAN_TOP_DIR}/build/pahole -G -M -C __sifields vmlinux'
alias npss='${FEYNMAN_TOP_DIR}/build/pahole -M -C __sifields vmlinux'
